Pz\WyskoczBundle\Entity\Place:
    type: entity
    table: null
    repositoryClass: Pz\WyskoczBundle\Entity\PlaceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: '64'
        description:
            type: text
        location:
            type: json_array
        etc:
            type: json_array
    lifecycleCallbacks: {  }
