security:
    encoders:
        Pz\UserBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        #in_memory:
        #    users:
        #        user:   { password: userpass, roles: { 'ROLE_USER' } }
        #        admin:  { password: adminpass, roles: { 'ROLE_ADMIN' } }
        #user_db:
        #    entity: { class: Pz\WyskoczBundle\Entity\User, property: username }

    firewalls:
         secured_area:
             pattern:    ^/
             anonymous: ~
             form_login:
                 provider:  fos_userbundle
                 login_path:  /login
                 check_path:  /login_check
             logout:
                 path:  /logout
                 target: /
         
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
