vote:
    pattern:  /
    defaults: { _controller: "WyskoczBundle:Vote:vote" }
    requirements: { _method: post }
    
get-votes:
    pattern: /get/{id}
    defaults: { _controller: "WyskoczBundle:Vote:getVotes" }
    
remove-votes:
    pattern: /remove/{userId}/{id}
    defaults: { _controller: "WyskoczBundle:Vote:removeVote" }
    
check-if-voted:
    pattern: /check/{userId}/{id}
    defaults: { _controller: "WyskoczBundle:Vote:checkIfVoted" }