<?php

namespace Pz\WyskoczBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Pz\WyskoczBundle\Entity\Vote;
/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    
    public function getVotes($id = NULL)
    {
        
        $dql = "SELECT AVG(v.value) FROM WyskoczBundle:Vote v " .
               "WHERE v.contentId = $id";
        $voteSum = $this->getEntityManager()
                        ->createQuery($dql)
                        ->getSingleScalarResult();
        return round($voteSum, 2);
        
    }
    
    public function checkIfVoted($userId, $id)
    {

        $vote = $this->findOneBy(array(
            'userId' => $userId,
            'contentId' => $id
        ));

        if(!empty($vote)) return true;
        else return false;
    }
    
}
