home:
    pattern:  /
    defaults: { _controller: WyskoczBundle:Page:index }

places_list:
    pattern:  /places
    defaults: { _controller: WyskoczBundle:Place:index }
    
how-to:
    pattern: /how-to
    defaults: { _controller: WyskoczBundle:Page:how_to }

admin:
    pattern:    /admin
    defaults: { _controller: WyskoczBundle:Admin:viewDashboard }
    
dashboard:
    pattern:    /admin/dashboard
    defaults: { _controller: WyskoczBundle:Admin:viewDashboard }

view_place:
    pattern:    /place/{id}
    defaults: { _controller: WyskoczBundle:Place:show }

WyskoczBundle_admin_page_:
    resource: "@WyskoczBundle/Resources/config/routing/page.yml"
    prefix:   /admin/page/

WyskoczBundle_admin_place:
    resource: "@WyskoczBundle/Resources/config/routing/place.yml"
    prefix:   /admin/place/
    
voting:
    resource: "@WyskoczBundle/Resources/config/routing/vote.yml"
    prefix:   /vote/