parameters:
#    wyskocz.example.class: Pz\WyskoczBundle\Example

services:
#    wyskocz.example:
#        class: %wyskocz.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
